name: shop_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  dio: ^4.0.6
  smooth_page_indicator: ^1.0.0+2
  flutter_form_builder: ^7.6.0
  form_builder_validators: ^8.3.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  fluid_bottom_nav_bar: ^1.3.0
  cached_network_image: ^3.2.2
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
